### ISSUE TITLE
Cant connect a peer

### ISSUE THREAD

**Issue by rafiton** [davidemiceli/chainode#1]
Hi David,
First of all - thanks for the nice project.

I managed to start a Blockchain network on a server with Block generator. Now, I tried to write/read from the network using a new peer on another machine but I cant get the peer to connect to the Blockchain network. I'm trying the following (I assume that the URL should be the generator's ip):

`const peer_id = blockchain.addpeer('<Blockchain ID>', 'http://<generator_ip_address>:60000');
`
And I'm getting the following error:

Creating a new peer...
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Error: ENOENT: no such file or directory, open 'data/<blockchain_id>/keys/private/<some_id>.pem'

Any idea?

Thanks
Rafi

**Comment by davidemiceli** [comment]
Hi @rafiton, at first thanks to you!

The problem I think is that you should put inside the `/data/<blockchain_id>/keys/private/<peer_id>.pem` folder the private key of the peer that you are using...

However I have the plan to refactor the project to have a first pre-release with a storage like RocksDB ore LevelDB, unit tests, and so on...
